[[project]]
name = "AliceBot"
desc = "使用 Python 协程编写的聊天机器人框架，拥有较高的执行效率。支持多种聊天协议适配，并提供了一套易于学习的插件语法用于用户编写插件实现聊天机器人具体功能。具有完全的类型注解支持、相对完善的文档和配套工具，支持插件和配置文件热重载。"
tags = ["python", "asyncio", "chatbot"]
links = [
    { name = "github", url = "https://github.com/AliceBotProject/alicebot" },
    { name = "docs", url = "https://docs.alicebot.dev/" },
]

[[project]]
name = "Lucia-lang"
desc = "一个受到了 Lua 和 Python 语言启发的轻量级、可嵌入的动态强类型编程语言。使用 Rust 语言实现了完整的词法分析、语法分析、语义分析、字节码生成和支持 GC 的基于栈的虚拟机。具有错误处理、头等函数、匿名函数、闭包、迭代器、运算符重载、安全导航运算符、尾调用优化等现代语言特性。"
tags = ["rust", "compiler", "vm"]
links = [
    { name = "github", url = "https://github.com/st1020/lucia-lang" },
    { name = "crates", url = "https://crates.io/crates/lucia-lang" },
    { name = "docs", url = "https://docs.rs/lucia-lang/latest/lucia_lang/" },
]

[[project]]
name = "Kita"
desc = "一个干净、优雅、简单的 Zola 博客主题。基于 hugo-paper 移植，做了不少样式调整并添加了目录、项目页面、存档页面、分类页面、Mermaid 支持、Admonition shortcode 等特性。"
tags = ["zola", "css", "blog"]
links = [
    { name = "github", url = "https://github.com/st1020/kita" },
    { name = "demo", url = "https://st1020.github.io/kita/" },
]

[[project]]
name = "Sophia-doc"
desc = "分析 Python 模块的 Docstring 并自动生成 Markdown 格式的 API 文档的工具，基于 PEP 257 – Docstring Conventions 和 PEP 484 – Type Hints 标准。支持分析 Python 函数或类的的类型注解，用于 AliceBot 项目的 API 文档生成。"
tags = ["python", "docstring"]
links = [{ name = "github", url = "https://github.com/st1020/sophia-doc" }]
