name: Docs Web Site Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify
        shell: bash

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          repo: st1020/st1020.github.io
          target_branch: master
          build_dir: public
          fqdn: st1020.top
        env:
          GH_PAT: ${{ secrets.GH_PAGES_TOKEN }}
